name: Build and Test

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.x'

      - name: Install dependencies
        run: |
          go mod download

      - name: Run testing
        run: go test -v ./...

      - name: Run go vet
        run: go vet ./...