name: GoSec Security Scan

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    # Run weekly on Mondays at 6:00 AM
    - cron: '0 6 * * 1'

permissions:
  contents: read
  security-events: write

jobs:
  gosec:
    name: Run gosec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.x'

      - name: Run gosec Security Scanner
        uses: securego/gosec@v2.22.9
        with:
          args: '-fmt sarif -out gosec-results.sarif -exclude-generated -severity high ./...'

      - name: Upload gosec results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: gosec-results.sarif

      - name: Run gosec with detailed output
        if: always()
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec -exclude-generated -confidence medium -severity medium -fmt=json -out=gosec-report.json ./... || true

      - name: Upload gosec report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gosec-report
          path: gosec-report.json
